#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -q hepxrt
#PBS -t 0-99
#PBS -m ae
#PBS -j oe
#PBS -M anthonykrose@gmail.com
cd /home/anthony.rose/Analysis/CMSSW_5_3_11_patch5/src
export SCRAM_ARCH=slc5_amd64_gcc462
source /home/hepxadmin/cmssw/cmsset_default.sh
eval `scramv1 runtime -sh`
cd /home/anthony.rose/Analysis/CMSSW_5_3_11_patch5/src/AnalysisTools/CutFlowAnalyzer/test/
./PAT.sh ${PBS_ARRAYID}
exit 0